//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/MyActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/MyActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MyActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MyActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MyActions"",
    ""maps"": [
        {
            ""name"": ""MouseActioMap"",
            ""id"": ""c82945ba-6b4d-4152-8ab3-107cd52320ae"",
            ""actions"": [
                {
                    ""name"": ""ChangePosX"",
                    ""type"": ""Value"",
                    ""id"": ""a364517a-ab5e-4d23-87e6-7a98b20f032b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangePosY"",
                    ""type"": ""Value"",
                    ""id"": ""672e6446-87ab-4617-b6df-c31b6ebfebd2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Kill"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9344b9b8-5309-4f23-84bf-985e18036dde"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""b6c5703f-d4e9-4802-a348-0a9398546ddf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2fd82c0-0956-48ca-87b6-3fd9ae32f31d"",
                    ""path"": ""<Mouse>/position/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePosX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""477c12ab-b7ce-4802-8bd7-eb444120cafc"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePosY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b249fbd1-0baf-45cf-85a4-d46725d153cd"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e72f2c0-de48-40ec-9cc7-728d5a746cd4"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MouseActioMap
        m_MouseActioMap = asset.FindActionMap("MouseActioMap", throwIfNotFound: true);
        m_MouseActioMap_ChangePosX = m_MouseActioMap.FindAction("ChangePosX", throwIfNotFound: true);
        m_MouseActioMap_ChangePosY = m_MouseActioMap.FindAction("ChangePosY", throwIfNotFound: true);
        m_MouseActioMap_Kill = m_MouseActioMap.FindAction("Kill", throwIfNotFound: true);
        m_MouseActioMap_Shoot = m_MouseActioMap.FindAction("Shoot", throwIfNotFound: true);
    }

    ~@MyActions()
    {
        UnityEngine.Debug.Assert(!m_MouseActioMap.enabled, "This will cause a leak and performance issues, MyActions.MouseActioMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseActioMap
    private readonly InputActionMap m_MouseActioMap;
    private List<IMouseActioMapActions> m_MouseActioMapActionsCallbackInterfaces = new List<IMouseActioMapActions>();
    private readonly InputAction m_MouseActioMap_ChangePosX;
    private readonly InputAction m_MouseActioMap_ChangePosY;
    private readonly InputAction m_MouseActioMap_Kill;
    private readonly InputAction m_MouseActioMap_Shoot;
    /// <summary>
    /// Provides access to input actions defined in input action map "MouseActioMap".
    /// </summary>
    public struct MouseActioMapActions
    {
        private @MyActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MouseActioMapActions(@MyActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MouseActioMap/ChangePosX".
        /// </summary>
        public InputAction @ChangePosX => m_Wrapper.m_MouseActioMap_ChangePosX;
        /// <summary>
        /// Provides access to the underlying input action "MouseActioMap/ChangePosY".
        /// </summary>
        public InputAction @ChangePosY => m_Wrapper.m_MouseActioMap_ChangePosY;
        /// <summary>
        /// Provides access to the underlying input action "MouseActioMap/Kill".
        /// </summary>
        public InputAction @Kill => m_Wrapper.m_MouseActioMap_Kill;
        /// <summary>
        /// Provides access to the underlying input action "MouseActioMap/Shoot".
        /// </summary>
        public InputAction @Shoot => m_Wrapper.m_MouseActioMap_Shoot;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MouseActioMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MouseActioMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MouseActioMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MouseActioMapActions" />
        public void AddCallbacks(IMouseActioMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseActioMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseActioMapActionsCallbackInterfaces.Add(instance);
            @ChangePosX.started += instance.OnChangePosX;
            @ChangePosX.performed += instance.OnChangePosX;
            @ChangePosX.canceled += instance.OnChangePosX;
            @ChangePosY.started += instance.OnChangePosY;
            @ChangePosY.performed += instance.OnChangePosY;
            @ChangePosY.canceled += instance.OnChangePosY;
            @Kill.started += instance.OnKill;
            @Kill.performed += instance.OnKill;
            @Kill.canceled += instance.OnKill;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MouseActioMapActions" />
        private void UnregisterCallbacks(IMouseActioMapActions instance)
        {
            @ChangePosX.started -= instance.OnChangePosX;
            @ChangePosX.performed -= instance.OnChangePosX;
            @ChangePosX.canceled -= instance.OnChangePosX;
            @ChangePosY.started -= instance.OnChangePosY;
            @ChangePosY.performed -= instance.OnChangePosY;
            @ChangePosY.canceled -= instance.OnChangePosY;
            @Kill.started -= instance.OnKill;
            @Kill.performed -= instance.OnKill;
            @Kill.canceled -= instance.OnKill;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MouseActioMapActions.UnregisterCallbacks(IMouseActioMapActions)" />.
        /// </summary>
        /// <seealso cref="MouseActioMapActions.UnregisterCallbacks(IMouseActioMapActions)" />
        public void RemoveCallbacks(IMouseActioMapActions instance)
        {
            if (m_Wrapper.m_MouseActioMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MouseActioMapActions.AddCallbacks(IMouseActioMapActions)" />
        /// <seealso cref="MouseActioMapActions.RemoveCallbacks(IMouseActioMapActions)" />
        /// <seealso cref="MouseActioMapActions.UnregisterCallbacks(IMouseActioMapActions)" />
        public void SetCallbacks(IMouseActioMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseActioMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseActioMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MouseActioMapActions" /> instance referencing this action map.
    /// </summary>
    public MouseActioMapActions @MouseActioMap => new MouseActioMapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MouseActioMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MouseActioMapActions.AddCallbacks(IMouseActioMapActions)" />
    /// <seealso cref="MouseActioMapActions.RemoveCallbacks(IMouseActioMapActions)" />
    public interface IMouseActioMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "ChangePosX" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangePosX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChangePosY" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangePosY(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Kill" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnKill(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Shoot" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShoot(InputAction.CallbackContext context);
    }
}
